version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    command: ng serve  --host=0.0.0.0 --port 4200
    volumes:
      - ./frontend/:/usr/src/frontend/
    ports:
      - 4205:4200
    restart: always
