# Generated by Django 3.1.4 on 2020-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
